<bug>
          <bug_id>1772</bug_id>
          
          <creation_ts>2008-12-17 12:07:00 +0100</creation_ts>
          <short_desc>data.singlevalue.Simple:testRemoveBinding fails in Chrome</short_desc>
          <delta_ts>2014-03-03 15:23:00 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>app.testrunner</component>
          <version>master</version>
          <rep_platform>Chrome</rep_platform>
          <op_sys>Windows</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>FIXED</resolution>
          
          
          
          
          
          <priority>P4</priority>
          <bug_severity>minor</bug_severity>
          <target_milestone>0.8.2</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Daniel Wagner">daniel.wagner</reporter>
          <assigned_to name="Martin Wittemann">martin.wittemann</assigned_to>
          
          <qa_contact name="qooxdoo bugs mailing list">qooxdoo-bugs</qa_contact>
          <cf_browser>Chrome</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>7016</commentid>
            <who name="Daniel Wagner">daniel.wagner</who>
            <bug_when>2008-12-17 12:07:41 +0100</bug_when>
            <thetext>qx.test.data.singlevalue.Simple:testRemoveBinding
Error message is: 
No exception thrown.: The raised exception does not have the expected type! function Error() { [native code] }
Stack trace:
qx.core.AssertionError:constructor
qx.core.AssertionError:constructor wrapper
function (condition, comment, msg)
function (callback, exception, re, msg)
qx.core.MAssert:assertException
qx.test.data.singlevalue.Simple:testRemoveBinding
function ()
qx.dev.unit.TestResult:run
qx.dev.unit.TestFunction:run
qx.dev.unit.TestLoader:runTests
function runtest()
function (e)
undefined:constructor
function wrappedFunction()
function (target,event)
function (target,type,clazz,args)
qx.core.Object:fireEvent
qx.event.Timer:_oninterval
function (event)</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>7020</commentid>
            <who name="Daniel Wagner">daniel.wagner</who>
            <bug_when>2008-12-17 12:12:07 +0100</bug_when>
            <thetext>To Martin.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>7061</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2008-12-17 14:26:03 +0100</bug_when>
            <thetext>Some kind of strange chrom behavior. The thrown error is not an instance of 
Error!!!</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>7062</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2008-12-17 14:26:16 +0100</bug_when>
            <thetext>Some kind of strange chrom behavior. The thrown error is not an instance of 
Error!!!</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>8228</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2009-03-03 17:14:31 +0100</bug_when>
            <thetext>Assigned.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>37853</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2014-03-03 15:23:00 +0100</bug_when>
            <thetext>Closed all bugs already shipped with a release.</thetext>
          </long_desc>
      
      

    </bug>