<bug>
          <bug_id>3175</bug_id>
          
          <creation_ts>2009-12-04 09:46:00 +0100</creation_ts>
          <short_desc>DeprecationWarning: BaseException.message has been deprecated as of Python 2.6</short_desc>
          <delta_ts>2014-03-03 15:22:30 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>app</component>
          <version>1.0-beta1</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>FIXED</resolution>
          
          
          
          
          
          <priority>P2</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>1.0</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Uwe Stahl">uwe.stahl</reporter>
          <assigned_to name="Thomas Herchenroeder">thron7</assigned_to>
          
          <qa_contact name="qooxdoo bugs mailing list">qooxdoo-bugs</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>15284</commentid>
            <who name="Uwe Stahl">uwe.stahl</who>
            <bug_when>2009-12-04 09:46:11 +0100</bug_when>
            <thetext>I once had a typo in the config.json.

This typo then caused the follwing warning 
when running &quot;generate.py clean&quot;:
DeprecationWarning: BaseException.message has been deprecated as of Python 2.6

This DeprecationWarning is gone after the typo in the file config.json has been fixed.

&gt;&gt;&gt; Jobs: clean
C:\ustahl\qooxdoo-1.0-beta1-sdk\tool\pylib\generator\config\Config.py:103: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  e.args = (e.message + &quot;\nFile: %s&quot; % fname,)
Traceback (most recent call last):
  File &quot;C:\ustahl\qooxdoo-1.0-beta1-sdk\tool\bin\generator.py&quot;, line 165, in &lt;module&gt;
    main()
  File &quot;C:\ustahl\qooxdoo-1.0-beta1-sdk\tool\bin\generator.py&quot;, line 112, in main
    config = Config(console, options.config, **options.letmacros)
  File &quot;C:\ustahl\qooxdoo-1.0-beta1-sdk\tool\pylib\generator\confi\Config.py&quot;,
line 56, in __init__
    self.__init_fname(data)
  File &quot;C:\ustahl\qooxdoo-1.0-beta1-sdk\tool\pylib\generator\config\Config.py&quot;,
line 104, in __init_fname
    raise e
ValueError: Expecting property name: line 52 column 7 (char 990)
File: config.json</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>15379</commentid>
            <who name="Andreas Ecker">qooxdoo</who>
            <bug_when>2009-12-07 16:13:35 +0100</bug_when>
            <thetext>Thomas, maybe there is a straightforward replacement to be compatible with future Python versions?</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>15392</commentid>
            <who name="Thomas Herchenroeder">thron7</who>
            <bug_when>2009-12-07 17:34:35 +0100</bug_when>
            <thetext>This is kind of a hairy problem. The .message property for excepions was only 
introduced with Python2.5, only to be deprecated in Python2.6, due to a shift 
in strategy to unify exception interfaces. So all that remains is the .args 
property, which I now use in the corresponding code, and which is the only 
property equally supported accross 2.5, 2.6 and beyond (and also 2.4, where 
.message wouldn&#39;t have worked at all!). But it feels like a kludge, as I make 
the assumption that an exception message is to be stored in .args[0], which is 
the common usage for all I can say, but who knows...

Also see this PEP: http://www.python.org/dev/peps/pep-0352/#retracted-ideas

With r20972.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>37705</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2014-03-03 15:22:30 +0100</bug_when>
            <thetext>Closed all bugs already shipped with a release.</thetext>
          </long_desc>
      
      

    </bug>