<bug>
          <bug_id>3731</bug_id>
          
          <creation_ts>2010-05-22 23:58:00 +0200</creation_ts>
          <short_desc>More specific exception for when same-origin test fails</short_desc>
          <delta_ts>2014-03-03 15:22:50 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>core.io.remote</component>
          <version>master</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>FIXED</resolution>
          
          
          <bug_file_loc>http://preview.tinyurl.com/378vju6</bug_file_loc>
          
          
          <priority>P3</priority>
          <bug_severity>enhancement</bug_severity>
          <target_milestone>1.1.1</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Alexander Boström">abo</reporter>
          <assigned_to name="Derrell Lipman">derrell.lipman</assigned_to>
          
          <qa_contact name="qooxdoo bugs mailing list">qooxdoo-bugs</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>18469</commentid>
            <who name="Alexander Boström">abo</who>
            <bug_when>2010-05-22 23:58:11 +0200</bug_when>
            <thetext>If a JSONRPC call fails the same-origin test you get &quot;Transport error 0: Unknown status code&quot;. If possible, a more specific error message would be useful.

To reproduce, go to the Playground and run:

var rpc = new qx.io.remote.Rpc(&quot;http://www.google.com/test&quot;,&quot;qooxdoo.test&quot;);
var h = function(result, exc) { alert(&quot;Exception during async call: &quot; + exc);};
rpc.callAsync(h, &quot;echo&quot;, &quot;Test&quot;);</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>18470</commentid>
            <who name="Derrell Lipman">derrell.lipman</who>
            <bug_when>2010-05-23 02:57:21 +0200</bug_when>
            <thetext>to me</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>18471</commentid>
            <who name="Derrell Lipman">derrell.lipman</who>
            <bug_when>2010-05-23 02:57:52 +0200</bug_when>
            <thetext>accept</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>18472</commentid>
            <who name="Derrell Lipman">derrell.lipman</who>
            <bug_when>2010-05-23 02:58:47 +0200</bug_when>
            <thetext>This is a tricky problem, since there doesn&#39;t appear to be any way to trap
it. There&#39;s a 405 error code that Firebug sees, but there&#39;s no place in the
onreadystate handler that that value is available.

Commit r22239 adds some &quot;suggested&quot; problems if error code 0 occurs. It tests to
see if the current page was loaded with a file: URL (a common cause of
questions on the mailing list), and if not, then it suggests that possibly
a cross-domain request was issued. This should at least get people thinking
along the right direction to more quickly solve the problem even though it&#39;s
not fool-proof.

Derrell
</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>18473</commentid>
            <who name="Alexander Boström">abo</who>
            <bug_when>2010-05-23 11:02:31 +0200</bug_when>
            <thetext>Awesome, thanks!</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>37827</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2014-03-03 15:22:50 +0100</bug_when>
            <thetext>Closed all bugs already shipped with a release.</thetext>
          </long_desc>
      
      

    </bug>