<bug>
          <bug_id>5649</bug_id>
          
          <creation_ts>2011-09-27 13:07:00 +0200</creation_ts>
          <short_desc>Cache is not updated when removing a branch of a library - wrong error message</short_desc>
          <delta_ts>2014-03-03 08:47:04 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>tool.generator</component>
          <version>master</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>RESOLVED</bug_status>
          <resolution>LATER</resolution>
          
          
          
          
          
          <priority>P4</priority>
          <bug_severity>enhancement</bug_severity>
          <target_milestone>unspecified</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Stefan Andersson">dev</reporter>
          <assigned_to name="Richard Sternagel">richard.sternagel</assigned_to>
          
          <qa_contact name="Richard Sternagel">richard.sternagel</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>26985</commentid>
            <who name="Stefan Andersson">dev</who>
            <bug_when>2011-09-27 13:07:38 +0200</bug_when>
            <thetext>two libs:

qxe.theme.modern.Color

and in the

contrib://trunk

also

qxe.theme.modern.Color

then

./generate.py

gives

  - Warning: Hint: Unknown global symbol referenced: qxe.theme.modern (cm.p.cm.re.theme.Appearance:15)

the error message here should be different like &quot;namespace clashing has occurred: qxe.theme.modern&quot; instead of the above.

then

the qxe.theme.modern and the directories are removed locally.

again

./generate.py

gives

  - Warning: Hint: Unknown global symbol referenced: qxe.theme.modern (cm.p.cm.re.theme.Appearance:15)

this error message should not have been thrown because there is no reason to it except in the cache which means that the cache has not been synchronized!

then

./generate.py distclean

and again

./generate.py

no errors anymore</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>26986</commentid>
            <who name="Stefan Andersson">dev</who>
            <bug_when>2011-09-27 13:09:26 +0200</bug_when>
            <thetext>This is poor design as the developer needs to trust the generator that it is doing right.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>35772</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2014-03-03 08:47:04 +0100</bug_when>
            <thetext>Move open issues to RESOLVED â€“ LATER, whose last comment is older than a year.</thetext>
          </long_desc>
      
      

    </bug>