<bug>
          <bug_id>6082</bug_id>
          
          <creation_ts>2012-01-27 16:06:00 +0100</creation_ts>
          <short_desc>&quot;create-application.py&quot; creates a skeleton with absolute path to the qooxdoo SDK</short_desc>
          <delta_ts>2014-03-03 15:19:14 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>tool.generator</component>
          <version>1.6</version>
          <rep_platform>All</rep_platform>
          <op_sys>Windows</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>INVALID</resolution>
          
          
          
          
          
          <priority>P3</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>1.6.1</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Alexander Steitz">alexander.steitz</reporter>
          <assigned_to name="Unassigned">none</assigned_to>
          
          <qa_contact name="Richard Sternagel">richard.sternagel</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>28383</commentid>
            <who name="Alexander Steitz">alexander.steitz</who>
            <bug_when>2012-01-27 16:06:20 +0100</bug_when>
            <thetext>Create a new skeleton (GUI one in my case) with &quot;create-application.py&quot;. The 
&quot;QOOXDOO_PATH&quot; is set as an absolute path like 

   &quot;C:/path/to/the/qooxdoo/SDK&quot;

And when generating a source version out of this application you end up with 
&quot;file:///&quot; paths in your JS file. If you use a local web server for development 
the application is not usable.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>28384</commentid>
            <who name="Thomas Herchenroeder">thron7</who>
            <bug_when>2012-01-27 16:24:40 +0100</bug_when>
            <thetext>What is the path of the created application? Is it perhaps on a different drive?</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>28385</commentid>
            <who name="Alexander Steitz">alexander.steitz</who>
            <bug_when>2012-01-27 16:30:55 +0100</bug_when>
            <thetext>No, same drive.

== Example ==

Path to qooxdoo: C:\users\aback\development\workspace\qooxdoo
Path to application: C:\users\aback\development\playground\testapp</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>28386</commentid>
            <who name="Thomas Herchenroeder">thron7</who>
            <bug_when>2012-01-27 16:45:04 +0100</bug_when>
            <thetext>Cannot confirm:

qooxdoo path: c:\tmp\qooxdoo-1.6-sdk\
application path: C:\Users\testuser\tmp\gui1
&quot;QOOXDOO_PATH&quot; : &quot;../../../../tmp/qooxdoo-1.6-sdk&quot;

How did you invoke create-application.py?
Which shell did you use?</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>28387</commentid>
            <who name="Alexander Steitz">alexander.steitz</who>
            <bug_when>2012-01-27 16:49:29 +0100</bug_when>
            <thetext>Seems to be that the msysgit console is the one to blame. When you use the Windows Powershell or the normal shell everything is fine.

-&gt; INVALID</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>36404</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2014-03-03 15:19:14 +0100</bug_when>
            <thetext>Closed all bugs already shipped with a release.</thetext>
          </long_desc>
      
      

    </bug>