<bug>
          <bug_id>6914</bug_id>
          
          <creation_ts>2012-10-22 08:50:00 +0200</creation_ts>
          <short_desc>Missing stack trace for errors in the layout queue</short_desc>
          <delta_ts>2014-03-03 15:19:13 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>desktop.layout</component>
          <version>master</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>FIXED</resolution>
          
          
          
          
          
          <priority>P2</priority>
          <bug_severity>enhancement</bug_severity>
          <target_milestone>2.1</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Uwe Stahl">uwe.stahl</reporter>
          <assigned_to name="Alexander Steitz">alexander.steitz</assigned_to>
          <cc>mustafa.sak</cc>
          <qa_contact name="Martin Wittemann">martin.wittemann</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>31014</commentid>
            <who name="Uwe Stahl">uwe.stahl</who>
            <bug_when>2012-10-22 08:50:29 +0200</bug_when>
            <thetext>Exceptions that occur when flushing the layout queue are logged by the following code:

              try {
                qx.ui.core.queue.Layout.flush();
              } catch (e) {
                qx.log.Logger.error(&quot;Error in the &#39;Layout&#39; queue:&quot; + e);
              }

This problem with this code is that the exception object is not passed as a seperate parameter. Therefore the stack trace is not logged.
The logging code should look like this:

                qx.log.Logger.error(&quot;Error in the &#39;Layout&#39; queue:&quot; + e, e);

All other Logger.error calls of the qooxdoo framework always pass the exception object as a separate object. Examples:
qx.log.Logger.error(this, &quot;Catched error on init: &quot;, exc);
qx.log.Logger.error(this, &quot;Dispatching event of type &quot; + evt.getType() + &quot; failed:&quot;, exc);


The error logs of our application show that many users are getting exceptions in the layout queue. But the message of this exception is not helpful: &quot;Error in the Layout queue: null is null or not an object&quot;. Therefore we need the stack trace to locate and fix the error.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>31045</commentid>
            <who name="Alexander Steitz">alexander.steitz</who>
            <bug_when>2012-10-24 15:41:04 +0200</bug_when>
            <thetext>Fixed with SHA 

   3edef6d4e141a7dc449d4dea2979f56cbe5e1f1f

on master.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>31406</commentid>
            <who name="Daniel Wagner">daniel.wagner</who>
            <bug_when>2012-11-21 10:43:15 +0100</bug_when>
            <thetext>*** Bug 6630 has been marked as a duplicate of this bug. ***</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>36394</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2014-03-03 15:19:13 +0100</bug_when>
            <thetext>Closed all bugs already shipped with a release.</thetext>
          </long_desc>
      
      

    </bug>