<bug>
          <bug_id>6986</bug_id>
          
          <creation_ts>2012-11-09 17:03:00 +0100</creation_ts>
          <short_desc>Unit tests of Logger and RingBuffer are throwing exceptions when changing the log level</short_desc>
          <delta_ts>2014-03-03 15:21:09 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>app</component>
          <version>master</version>
          <rep_platform>Firefox</rep_platform>
          <op_sys>Windows</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>FIXED</resolution>
          
          
          
          
          
          <priority>P3</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>2.0.3</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Alexander Steitz">alexander.steitz</reporter>
          <assigned_to name="Daniel Wagner">daniel.wagner</assigned_to>
          
          <qa_contact name="Martin Wittemann">martin.wittemann</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>31306</commentid>
            <who name="Alexander Steitz">alexander.steitz</who>
            <bug_when>2012-11-09 17:03:26 +0100</bug_when>
            <thetext>When running the unit tests &quot;qx.test.log.Logger.testLogException&quot; and 
&quot;qx.test.log.RingBuffer.testLog&quot; and changing the log-level of the TestRunner 
application an exception is thrown.

Changing back the log level &quot;solves&quot; this issue.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>31319</commentid>
            <who name="Daniel Wagner">daniel.wagner</who>
            <bug_when>2012-11-12 12:48:11 +0100</bug_when>
            <thetext>Fixed with
e3031cdffba9cfea33210b937a5005ca690e93bd (branch_2_0_x)
90897bc6d319b7b98a0c0723feb74b29c6e959c6 (master)</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>31320</commentid>
            <who name="Alexander Steitz">alexander.steitz</who>
            <bug_when>2012-11-12 18:21:42 +0100</bug_when>
            <thetext>The unit test &quot;qx.test.log.RingBuffer:testLog&quot; still throws an error. It only runs without an error if the log level is set to &quot;debug&quot;. All other log level are not working.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>31323</commentid>
            <who name="Daniel Wagner">daniel.wagner</who>
            <bug_when>2012-11-13 09:08:12 +0100</bug_when>
            <thetext>Fixed with
f4e2688c9119aa9c5a13bf8c3d83af7f327e6339 (master)
dd9260ee66ae0699c6d726712c2510bbfac05def (branch_2_0_x)</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>37180</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2014-03-03 15:21:09 +0100</bug_when>
            <thetext>Closed all bugs already shipped with a release.</thetext>
          </long_desc>
      
      

    </bug>