<bug>
          <bug_id>7740</bug_id>
          
          <creation_ts>2013-09-16 13:31:00 +0200</creation_ts>
          <short_desc>Exception on &quot;generate.py&quot; with empty string as macro value</short_desc>
          <delta_ts>2014-09-23 08:22:27 +0200</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>tool.generator</component>
          <version>3.0.1</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>RESOLVED</bug_status>
          <resolution>LATER</resolution>
          
          
          
          
          
          <priority>P3</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>unspecified</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter>markus.lauer</reporter>
          <assigned_to name="Unassigned">none</assigned_to>
          
          <qa_contact name="Richard Sternagel">richard.sternagel</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>33923</commentid>
            <who name="">markus.lauer</who>
            <bug_when>2013-09-16 13:31:52 +0200</bug_when>
            <thetext>If you pass any macro on command line with an empty string as value, generate.py throws an exception. 

app$ ./generate.py -m TEST: 
Traceback (most recent call last): 
  File &quot;/home/user/public_html/qooxdoo-3.0.1-sdk/tool/bin/generator.py&quot;, line 247, in &lt;module&gt;
    main() 
  File &quot;/home/user/public_html/qooxdoo-3.0.1-sdk/tool/bin/generator.py&quot;, line 117, in main 
    (options, args) = GeneratorArguments(option_class=ExtendAction).parse_args(sys.argv[1:]) 
  File &quot;/usr/lib/python2.7/optparse.py&quot;, line 1399, in parse_args 
    stop = self._process_args(largs, rargs, values) 
  File &quot;/usr/lib/python2.7/optparse.py&quot;, line 1443, in _process_args 
    self._process_short_opts(rargs, values) 
  File &quot;/usr/lib/python2.7/optparse.py&quot;, line 1550, in _process_short_opts 
    option.process(opt, value, values, self) 
  File &quot;/usr/lib/python2.7/optparse.py&quot;, line 788, in process 
    self.action, self.dest, opt, value, values, parser) 
  File &quot;/home/user/public_html/qooxdoo-3.0.1-sdk/tool/pylib/misc/ExtendAction.py&quot;, line 45, in take_action 
    if keyval[1][0] in [&quot;[&quot;, &quot;{&quot;]: # decode a Json value 
IndexError: string index out of range 





I think empty strings should be valid values. Anyway, if they&#39;re not, a proper error message would be fine.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>33924</commentid>
            <who name="">markus.lauer</who>
            <bug_when>2013-09-16 13:35:42 +0200</bug_when>
            <thetext>Forgot my environment:

$ uname -a
Linux hostname 3.2.0-35-generic #55-Ubuntu SMP Wed Dec 5 17:42:16 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

$ echo $SHELL
/bin/bash



(In reply to comment #0)
&gt; If you pass any macro on command line with an empty string as value,
&gt; generate.py throws an exception. 
&gt; 
&gt; app$ ./generate.py -m TEST: 
&gt; Traceback (most recent call last): 
&gt;   File &quot;/home/user/public_html/qooxdoo-3.0.1-sdk/tool/bin/generator.py&quot;, line
&gt; 247, in &lt;module&gt;
&gt;     main() 
&gt;   File &quot;/home/user/public_html/qooxdoo-3.0.1-sdk/tool/bin/generator.py&quot;, line
&gt; 117, in main 
&gt;     (options, args) =
&gt; GeneratorArguments(option_class=ExtendAction).parse_args(sys.argv[1:]) 
&gt;   File &quot;/usr/lib/python2.7/optparse.py&quot;, line 1399, in parse_args 
&gt;     stop = self._process_args(largs, rargs, values) 
&gt;   File &quot;/usr/lib/python2.7/optparse.py&quot;, line 1443, in _process_args 
&gt;     self._process_short_opts(rargs, values) 
&gt;   File &quot;/usr/lib/python2.7/optparse.py&quot;, line 1550, in _process_short_opts 
&gt;     option.process(opt, value, values, self) 
&gt;   File &quot;/usr/lib/python2.7/optparse.py&quot;, line 788, in process 
&gt;     self.action, self.dest, opt, value, values, parser) 
&gt;   File
&gt; &quot;/home/user/public_html/qooxdoo-3.0.1-sdk/tool/pylib/misc/ExtendAction.py&quot;,
&gt; line 45, in take_action 
&gt;     if keyval[1][0] in [&quot;[&quot;, &quot;{&quot;]: # decode a Json value 
&gt; IndexError: string index out of range 
&gt; 
&gt; 
&gt; 
&gt; 
&gt; 
&gt; I think empty strings should be valid values. Anyway, if they&#39;re not, a proper
&gt; error message would be fine.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>41202</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2014-09-23 08:22:27 +0200</bug_when>
            <thetext>Move open issues to RESOLVED â€“ LATER, whose last comment is older than a year.</thetext>
          </long_desc>
      
      

    </bug>